services:
  web:
    image: nginx:stable
    container_name: nginx
    ports:
      - 81:80
    volumes:
      - ./src1:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build: ./docker/php
    container_name: php-fpm
    volumes:
      - ./src1:/var/www/html
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15.1
    container_name: postgres
    environment:
       POSTGRES_DB: ${POSTGRES_DB} # Имя базы данных
       POSTGRES_USER: ${POSTGRES_USER}   # Пользователь базы данных
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль пользователя (для реальных проектов лучше через .env)
    #volumes:
     # - ./docker/db_data:/var/lib/postgresql/data # Персистентное хранение данных БД на хосте
    ports:
      - 54324:5432
